package fm.corus.android.data.remote

import io.ktor.client.HttpClient
import io.ktor.client.engine.mock.MockEngine
import io.ktor.client.engine.mock.MockRequestHandleScope
import io.ktor.client.engine.mock.respond
import io.ktor.client.request.HttpRequestData
import io.ktor.client.request.HttpResponseData
import io.ktor.http.HttpHeaders
import io.ktor.http.HttpStatusCode
import io.ktor.http.content.TextContent
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Unit coverage for [TidalPlaylistService] against a mocked TIDAL v2 API. Guards
 * the request shapes (paths, countryCode query, JSON:API bodies, 20-item
 * batching), the country fallback, and 401/403 → InsufficientScope mapping.
 *
 * NOTE: the real v2 JSON:API shapes are unverified on device (see the service's
 * header warning); these tests pin the *client's* behavior, not TIDAL's contract.
 */
class TidalPlaylistServiceTest {

    private val recorded = mutableListOf<HttpRequestData>()

    private fun bodyText(request: HttpRequestData): String =
        (request.body as? TextContent)?.text.orEmpty()

    private fun serviceWith(handler: suspend MockRequestHandleScope.(HttpRequestData) -> HttpResponseData): TidalPlaylistService {
        recorded.clear()
        val engine = MockEngine { request ->
            recorded += request
            handler(request)
        }
        return TidalPlaylistService(HttpClient(engine))
    }

    @Test
    fun `creates playlist, applies countryCode, batches adds in 20s`() = runTest {
        val service = serviceWith { request ->
            val path = request.url.encodedPath
            when {
                path.endsWith("/users/me") ->
                    respond("""{"data":{"attributes":{"countryCode":"NO"}}}""", HttpStatusCode.OK)
                path.endsWith("/playlists") ->
                    respond("""{"data":{"id":"PL1"}}""", HttpStatusCode.Created)
                path.contains("/relationships/items") ->
                    respond("", HttpStatusCode.Created)
                else -> respond("", HttpStatusCode.NotFound)
            }
        }

        val ids = (1..25).map { "t$it" }
        val result = service.createPlaylist("Corus Feed", "Generated by Corus", ids, "tok")

        assertEquals("https://tidal.com/playlist/PL1", result.url)
        assertEquals(25, result.addedCount)
        assertEquals(25, result.requestedCount)

        // /users/me, POST /playlists, then two batched item adds (20 + 5).
        val itemCalls = recorded.filter { it.url.encodedPath.contains("/relationships/items") }
        assertEquals(2, itemCalls.size)
        assertEquals(20, bodyText(itemCalls[0]).split("\"type\":\"tracks\"").size - 1)
        assertEquals(5, bodyText(itemCalls[1]).split("\"type\":\"tracks\"").size - 1)

        // countryCode from /users/me threaded onto the create + add calls.
        val createCall = recorded.first { it.url.encodedPath.endsWith("/playlists") }
        assertEquals("NO", createCall.url.parameters["countryCode"])
        assertEquals("Bearer tok", createCall.headers[HttpHeaders.Authorization])
        // create body carries the playlist attributes.
        assertTrue(bodyText(createCall).contains("\"name\":\"Corus Feed\""))
        assertTrue(bodyText(createCall).contains("\"accessType\":\"UNLISTED\""))
    }

    @Test
    fun `falls back to US country when users-me fails`() = runTest {
        val service = serviceWith { request ->
            val path = request.url.encodedPath
            when {
                path.endsWith("/users/me") -> respond("", HttpStatusCode.InternalServerError)
                path.endsWith("/playlists") -> respond("""{"data":{"id":"PL9"}}""", HttpStatusCode.Created)
                else -> respond("", HttpStatusCode.Created)
            }
        }

        service.createPlaylist("X", "Y", listOf("a"), "tok")

        val createCall = recorded.first { it.url.encodedPath.endsWith("/playlists") }
        assertEquals("US", createCall.url.parameters["countryCode"])
    }

    @Test
    fun `401 on create maps to InsufficientScope`() = runTest {
        val service = serviceWith { request ->
            val path = request.url.encodedPath
            when {
                path.endsWith("/users/me") -> respond("""{"data":{"attributes":{"countryCode":"US"}}}""", HttpStatusCode.OK)
                else -> respond("", HttpStatusCode.Unauthorized)
            }
        }

        val ex = runCatching { service.createPlaylist("X", "Y", listOf("a"), "tok") }.exceptionOrNull()
        assertTrue(ex is TidalPlaylistService.PlaylistException.InsufficientScope)
    }

    @Test
    fun `empty track list throws NoTracks without any HTTP call`() = runTest {
        val service = serviceWith { respond("", HttpStatusCode.OK) }

        val ex = runCatching { service.createPlaylist("X", "Y", emptyList(), "tok") }.exceptionOrNull()
        assertTrue(ex is TidalPlaylistService.PlaylistException.NoTracks)
        assertTrue(recorded.isEmpty())
    }

    @Test
    fun `missing playlist id surfaces RequestFailed`() = runTest {
        val service = serviceWith { request ->
            val path = request.url.encodedPath
            when {
                path.endsWith("/users/me") -> respond("""{"data":{"attributes":{"countryCode":"US"}}}""", HttpStatusCode.OK)
                else -> respond("{}", HttpStatusCode.Created)
            }
        }

        val ex = runCatching { service.createPlaylist("X", "Y", listOf("a"), "tok") }.exceptionOrNull()
        assertTrue(ex is TidalPlaylistService.PlaylistException.RequestFailed)
    }
}
