package fm.corus.android.ui.components

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import fm.corus.android.R

/** Accepted iOS 1.6.8 display copy, using Android's active resource locale. */
@Composable
fun parityCopy(text: String): String = when (text) {
    "" -> stringResource(fm.corus.android.localization.CorusStrings.parity_da39a3ee5e6b)
    " " -> stringResource(fm.corus.android.localization.CorusStrings.parity_b858cb282617)
    " · " -> stringResource(fm.corus.android.localization.CorusStrings.parity_d3dacf895c16)
    "%@" -> stringResource(R.string.parity_99e693f8cd0c)
    "%lld" -> stringResource(R.string.parity_16070acfe083)
    ", " -> stringResource(fm.corus.android.localization.CorusStrings.parity_d3bc9a378daa)
    "0" -> stringResource(fm.corus.android.localization.CorusStrings.parity_b6589fc6ab0d)
    "@" -> stringResource(fm.corus.android.localization.CorusStrings.parity_9a78211436f6)
    "Album" -> stringResource(fm.corus.android.localization.CorusStrings.share_album_word)
    "All" -> stringResource(fm.corus.android.localization.CorusStrings.concert_tab_all)
    "All communities" -> stringResource(fm.corus.android.localization.CorusStrings.map_all_communities)
    "All messages" -> stringResource(fm.corus.android.localization.CorusStrings.parity_29207dfdb31a)
    "Anyone on Corus can see your city." -> stringResource(fm.corus.android.localization.CorusStrings.parity_253657df34e4)
    "Anywhere" -> stringResource(fm.corus.android.localization.CorusStrings.parity_cdf9bbefc769)
    "Artist" -> stringResource(fm.corus.android.localization.CorusStrings.profile_artist_fallback)
    "Back" -> stringResource(fm.corus.android.localization.CorusStrings.common_back)
    "Back to Search" -> stringResource(fm.corus.android.localization.CorusStrings.parity_ca41295be45f)
    "Blue Tie-Dye" -> stringResource(fm.corus.android.localization.CorusStrings.style_vinyl_blue_tie_dye)
    "Books" -> stringResource(fm.corus.android.localization.CorusStrings.parity_4a7fdd8c1742)
    "Brat Green" -> stringResource(fm.corus.android.localization.CorusStrings.style_vinyl_brat_green)
    "CITY" -> stringResource(fm.corus.android.localization.CorusStrings.parity_55f447a461be)
    "Cancel" -> stringResource(fm.corus.android.localization.CorusStrings.common_cancel)
    "Change" -> stringResource(fm.corus.android.localization.CorusStrings.parity_64fbd995d3b6)
    "Change this anytime." -> stringResource(fm.corus.android.localization.CorusStrings.parity_5aff5a1f6aa7)
    "Channel Orange" -> stringResource(fm.corus.android.localization.CorusStrings.style_vinyl_channel_orange)
    "Choose a city" -> stringResource(fm.corus.android.localization.CorusStrings.concert_choose_city)
    "City" -> stringResource(fm.corus.android.localization.CorusStrings.concert_city_search)
    "Claim artist page" -> stringResource(fm.corus.android.localization.CorusStrings.parity_51dc1092be23)
    "Claim this artist page" -> stringResource(fm.corus.android.localization.CorusStrings.parity_512c233088e1)
    "Clear search" -> stringResource(fm.corus.android.localization.CorusStrings.map_cd_clear_search)
    "Close" -> stringResource(fm.corus.android.localization.CorusStrings.concert_close)
    "Close city" -> stringResource(fm.corus.android.localization.CorusStrings.parity_945c744fba00)
    "Comments" -> stringResource(fm.corus.android.localization.CorusStrings.activity_filter_comments)
    "Community" -> stringResource(fm.corus.android.localization.CorusStrings.parity_bfd58ee3a270)
    "Community chat" -> stringResource(fm.corus.android.localization.CorusStrings.parity_c2f4d4164ba5)
    "Compilation" -> stringResource(fm.corus.android.localization.CorusStrings.parity_aad755de4295)
    "Connect Audiomack" -> stringResource(fm.corus.android.localization.CorusStrings.parity_9885182153f7)
    "Contact email" -> stringResource(fm.corus.android.localization.CorusStrings.parity_726a1ceebd2e)
    "Copied!" -> stringResource(fm.corus.android.localization.CorusStrings.parity_b7c3ca0ee379)
    "Corus Map" -> stringResource(fm.corus.android.localization.CorusStrings.parity_16994bdea573)
    "Corus city map" -> stringResource(fm.corus.android.localization.CorusStrings.parity_6897038c5beb)
    "Corus will group you in your nearest city and never share or store your precise location." -> stringResource(fm.corus.android.localization.CorusStrings.parity_a76c16dc843a)
    "Cotton Candy" -> stringResource(fm.corus.android.localization.CorusStrings.style_vinyl_cotton_candy)
    "Couldn't share your city" -> stringResource(fm.corus.android.localization.CorusStrings.parity_4c19241c7fd4)
    "Couldn’t load map. Try again." -> stringResource(fm.corus.android.localization.CorusStrings.parity_5094bccc54b1)
    "Custom profile badge" -> stringResource(fm.corus.android.localization.CorusStrings.parity_5c419b5daae2)
    "Depression Cherry" -> stringResource(fm.corus.android.localization.CorusStrings.style_vinyl_depression_cherry)
    "Discography" -> stringResource(fm.corus.android.localization.CorusStrings.parity_19a4b0a062c8)
    "Disconnect" -> stringResource(fm.corus.android.localization.CorusStrings.music_service_spotify_sign_out)
    "Discover from real people you match with. Support an independent community." -> stringResource(fm.corus.android.localization.CorusStrings.parity_c4b871e217c3)
    "Done" -> stringResource(fm.corus.android.localization.CorusStrings.done_finish)
    "Don’t share. You can still explore." -> stringResource(fm.corus.android.localization.CorusStrings.parity_5a140248c0bb)
    "Everyone" -> stringResource(fm.corus.android.localization.CorusStrings.parity_c756f6af1f03)
    "Explore the Corus Map" -> stringResource(fm.corus.android.localization.CorusStrings.parity_2f5ac9fb4c6f)
    "Export playlists" -> stringResource(fm.corus.android.localization.CorusStrings.parity_3a03d227b2f2)
    "FOLLOW" -> stringResource(fm.corus.android.localization.CorusStrings.parity_0137b9ad82f9)
    "FOLLOWING" -> stringResource(fm.corus.android.localization.CorusStrings.parity_f0de6c8aaa3f)
    "Film" -> stringResource(fm.corus.android.localization.CorusStrings.search_tab_film)
    "Films posted by people around the world." -> stringResource(fm.corus.android.localization.CorusStrings.parity_b2dc2c4efc03)
    "Find people by city" -> stringResource(fm.corus.android.localization.CorusStrings.parity_08f45c68e588)
    "Find your kind of people. Explore your full taste match list and discover what you have in common." -> stringResource(fm.corus.android.localization.CorusStrings.taste_discovery_subtitle)
    "Finding your city" -> stringResource(fm.corus.android.localization.CorusStrings.map_finding_city)
    "Following" -> stringResource(fm.corus.android.localization.CorusStrings.following_status)
    "From" -> stringResource(fm.corus.android.localization.CorusStrings.parity_3f66052a107e)
    "Full name" -> stringResource(fm.corus.android.localization.CorusStrings.parity_eeb692087d62)
    "Galaxy" -> stringResource(fm.corus.android.localization.CorusStrings.style_vinyl_galaxy)
    "Get the most out of Corus" -> stringResource(fm.corus.android.localization.CorusStrings.parity_42e01b33038c)
    "Got it" -> stringResource(fm.corus.android.localization.CorusStrings.feed_energy_got_it)
    "Group chat" -> stringResource(fm.corus.android.localization.CorusStrings.parity_323d2167a2f2)
    "Grow your cluster. Invite your friends to join Corus." -> stringResource(fm.corus.android.localization.CorusStrings.parity_41c2e9e827d6)
    "How can we verify your connection to this artist?" -> stringResource(fm.corus.android.localization.CorusStrings.parity_d88e57bb0db6)
    "Icy Blue" -> stringResource(fm.corus.android.localization.CorusStrings.style_vinyl_icy_blue)
    "If you share, people see your city — not your street or a live pin. You can change this anytime." -> stringResource(fm.corus.android.localization.CorusStrings.parity_5d6f27fadf8c)
    "Invite friends" -> stringResource(fm.corus.android.localization.CorusStrings.parity_129daef04d80)
    "Join chat" -> stringResource(fm.corus.android.localization.CorusStrings.map_join_chat)
    "Join me on Corus — share music & movies with friends!" -> stringResource(fm.corus.android.localization.CorusStrings.parity_55abf8455833)
    "Join the Club" -> stringResource(fm.corus.android.localization.CorusStrings.club_cta_join)
    "Join the Corus Club" -> stringResource(fm.corus.android.localization.CorusStrings.settings_row_join_club)
    "Keep discovering films. Unlock unlimited Watch Mode with Corus Club." -> stringResource(fm.corus.android.localization.CorusStrings.parity_61453a62e3b0)
    "Keep listening around the world. Unlock unlimited Listen Mode with Corus Club." -> stringResource(fm.corus.android.localization.CorusStrings.parity_e1a462a5938c)
    "Last free song · Explore Club" -> stringResource(fm.corus.android.localization.CorusStrings.parity_21b98d7b5820)
    "Last free trailer · Explore Club" -> stringResource(fm.corus.android.localization.CorusStrings.parity_dfbdf908e6f2)
    "Latest post" -> stringResource(fm.corus.android.localization.CorusStrings.map_latest_post)
    "Lavender" -> stringResource(fm.corus.android.localization.CorusStrings.style_vinyl_lavender)
    "Like" -> stringResource(fm.corus.android.localization.CorusStrings.comment_like_action)
    "Likes" -> stringResource(fm.corus.android.localization.CorusStrings.likes_title)
    "Link to an official page that supports your role and explain your affiliation (at least 20 characters). Please don’t include passwords or identity documents. Your details will be sent privately to the Corus team for review." -> stringResource(fm.corus.android.localization.CorusStrings.parity_1af3aa5c3fea)
    "Links" -> stringResource(fm.corus.android.localization.CorusStrings.destination_links)
    "List" -> stringResource(fm.corus.android.localization.CorusStrings.parity_a1fffaaafb7c)
    "Listen" -> stringResource(fm.corus.android.localization.CorusStrings.parity_c518fb067439)
    "Listen Mode" -> stringResource(fm.corus.android.localization.CorusStrings.parity_820020256535)
    "Listen preview · %lld songs left · Explore Club" -> stringResource(R.string.parity_36262d2bbd0a)
    "Listen to music posted by people in the countries you choose." -> stringResource(fm.corus.android.localization.CorusStrings.parity_9e76f7b2d5ca)
    "Load more" -> stringResource(fm.corus.android.localization.CorusStrings.concert_see_more)
    "Load more people" -> stringResource(fm.corus.android.localization.CorusStrings.parity_ff35c3fdb683)
    "Loading" -> stringResource(fm.corus.android.localization.CorusStrings.post_aria_loading)
    "Loading people…" -> stringResource(fm.corus.android.localization.CorusStrings.parity_c32673783563)
    "Loading tour dates" -> stringResource(fm.corus.android.localization.CorusStrings.parity_d0611fff32c6)
    "Loading…" -> stringResource(fm.corus.android.localization.CorusStrings.common_loading)
    "Location access is needed to share your city. Enable it and try again." -> stringResource(fm.corus.android.localization.CorusStrings.parity_f5340afd9028)
    "Map" -> stringResource(fm.corus.android.localization.CorusStrings.parity_ab478f3efc84)
    "Marquee" -> stringResource(fm.corus.android.localization.CorusStrings.style_frame_marquee)
    "Maybe later" -> stringResource(fm.corus.android.localization.CorusStrings.parity_27ad1d833422)
    "Mentions only" -> stringResource(fm.corus.android.localization.CorusStrings.parity_1dbdcfefae45)
    "Merch" -> stringResource(fm.corus.android.localization.CorusStrings.destination_merch)
    "Merch & vinyl" -> stringResource(fm.corus.android.localization.CorusStrings.parity_12b87dbbadf8)
    "Message, meet up, or go to concerts together." -> stringResource(fm.corus.android.localization.CorusStrings.parity_d1af6c07c8e7)
    "Monthly" -> stringResource(fm.corus.android.localization.CorusStrings.club_plan_monthly)
    "More" -> stringResource(fm.corus.android.localization.CorusStrings.full_player_cd_more)
    "Music" -> stringResource(fm.corus.android.localization.CorusStrings.search_tab_music)
    "Music posted by people around the world." -> stringResource(fm.corus.android.localization.CorusStrings.parity_640127a5a8b7)
    "Muted" -> stringResource(fm.corus.android.localization.CorusStrings.profile_muted)
    "New message" -> stringResource(fm.corus.android.localization.CorusStrings.new_message_action)
    "New releases" -> stringResource(fm.corus.android.localization.CorusStrings.search_section_new_release_films)
    "Next" -> stringResource(fm.corus.android.localization.CorusStrings.full_player_cd_next)
    "Next city" -> stringResource(fm.corus.android.localization.CorusStrings.map_cd_next_city)
    "Next page" -> stringResource(fm.corus.android.localization.CorusStrings.parity_4bfc194b68a3)
    "No films yet" -> stringResource(fm.corus.android.localization.CorusStrings.parity_6683bd1a6bb4)
    "No one" -> stringResource(fm.corus.android.localization.CorusStrings.parity_41c06c15c761)
    "No one sees you until you choose." -> stringResource(fm.corus.android.localization.CorusStrings.parity_c758598ebf50)
    "No people are sharing their city for this selection yet." -> stringResource(fm.corus.android.localization.CorusStrings.parity_35655136006c)
    "No people to show for this filter." -> stringResource(fm.corus.android.localization.CorusStrings.parity_1ed0d88c7eb5)
    "No trophies yet" -> stringResource(fm.corus.android.localization.CorusStrings.parity_b7bbf3d235d6)
    "No users found" -> stringResource(fm.corus.android.localization.CorusStrings.parity_612eb3c64c41)
    "Not now" -> stringResource(fm.corus.android.localization.CorusStrings.parity_e45714907316)
    "Notifications" -> stringResource(fm.corus.android.localization.CorusStrings.settings_row_notifications)
    "OK" -> stringResource(fm.corus.android.localization.CorusStrings.common_ok)
    "Off" -> stringResource(fm.corus.android.localization.CorusStrings.settings_push_off)
    "Only accounts you follow." -> stringResource(fm.corus.android.localization.CorusStrings.parity_11546013dc6e)
    "Open chat" -> stringResource(fm.corus.android.localization.CorusStrings.map_open_chat)
    "Or select countries below, then press Start." -> stringResource(fm.corus.android.localization.CorusStrings.parity_43b1743b11a0)
    "Orange Tie-Dye" -> stringResource(fm.corus.android.localization.CorusStrings.style_vinyl_orange_tie_dye)
    "Peach" -> stringResource(fm.corus.android.localization.CorusStrings.style_vinyl_peach)
    "People I follow" -> stringResource(fm.corus.android.localization.CorusStrings.parity_f6f88f09f389)
    "People can find you in the city you choose." -> stringResource(fm.corus.android.localization.CorusStrings.parity_38be27f3fd1c)
    "Photo" -> stringResource(fm.corus.android.localization.CorusStrings.thread_photo)
    "Pink" -> stringResource(fm.corus.android.localization.CorusStrings.style_vinyl_pink)
    "Play" -> stringResource(fm.corus.android.localization.CorusStrings.voice_note_cd_play)
    "Please try again." -> stringResource(fm.corus.android.localization.CorusStrings.parity_83a6fd7b7878)
    "Popular" -> stringResource(fm.corus.android.localization.CorusStrings.destination_popular)
    "Post your first film" -> stringResource(fm.corus.android.localization.CorusStrings.parity_4702964a2944)
    "Post your first song" -> stringResource(fm.corus.android.localization.CorusStrings.parity_f58d094c6ad7)
    "Previous" -> stringResource(fm.corus.android.localization.CorusStrings.parity_50f94286ba30)
    "Previous city" -> stringResource(fm.corus.android.localization.CorusStrings.parity_c21c3d0c6b59)
    "Previous page" -> stringResource(fm.corus.android.localization.CorusStrings.parity_81f547195bef)
    "Profile" -> stringResource(fm.corus.android.localization.CorusStrings.nav_profile)
    "Profile customization" -> stringResource(fm.corus.android.localization.CorusStrings.parity_8624339e6a12)
    "Purple Tie-Dye" -> stringResource(fm.corus.android.localization.CorusStrings.style_vinyl_purple_tie_dye)
    "Recent posts" -> stringResource(fm.corus.android.localization.CorusStrings.parity_5690d9243775)
    "Repost" -> stringResource(fm.corus.android.localization.CorusStrings.compose_repost)
    "Represent this artist? Share a few details so we can review your request to claim this page." -> stringResource(fm.corus.android.localization.CorusStrings.parity_8adb8b29a148)
    "Request submitted" -> stringResource(fm.corus.android.localization.CorusStrings.parity_43dc47b2550f)
    "Retry" -> stringResource(fm.corus.android.localization.CorusStrings.common_retry)
    "Retry loading people" -> stringResource(fm.corus.android.localization.CorusStrings.parity_e3fe3e9ea782)
    "Role" -> stringResource(fm.corus.android.localization.CorusStrings.parity_c3f104d13657)
    "Save" -> stringResource(fm.corus.android.localization.CorusStrings.save_post)
    "Save Changes" -> stringResource(fm.corus.android.localization.CorusStrings.parity_fa2984b367b8)
    "Saving..." -> stringResource(fm.corus.android.localization.CorusStrings.compose_draft_saving)
    "Search" -> stringResource(fm.corus.android.localization.CorusStrings.nav_search)
    "Search KLIPY" -> stringResource(fm.corus.android.localization.CorusStrings.parity_9e867d1a518b)
    "Search cities" -> stringResource(fm.corus.android.localization.CorusStrings.parity_8008bef0fc1f)
    "Search cities or countries" -> stringResource(fm.corus.android.localization.CorusStrings.parity_04142689eeeb)
    "Search cities or people" -> stringResource(fm.corus.android.localization.CorusStrings.parity_72e7521d243f)
    "Search films" -> stringResource(fm.corus.android.localization.CorusStrings.parity_4579de70a18f)
    "Search songs" -> stringResource(fm.corus.android.localization.CorusStrings.parity_9de9debbfd35)
    "Search username" -> stringResource(fm.corus.android.localization.CorusStrings.parity_8d232b28b92f)
    "See more" -> stringResource(fm.corus.android.localization.CorusStrings.parity_see_more)
    "See taste matches near you on the map — people who share your music and film taste." -> stringResource(fm.corus.android.localization.CorusStrings.parity_017b94f9a480)
    "Share" -> stringResource(fm.corus.android.localization.CorusStrings.concert_share)
    "Share another film" -> stringResource(fm.corus.android.localization.CorusStrings.parity_94023f5a4a52)
    "Share your city" -> stringResource(fm.corus.android.localization.CorusStrings.parity_6e01c19a0c7a)
    "Share your city, not your exact location." -> stringResource(fm.corus.android.localization.CorusStrings.parity_31fab0859db4)
    "Sharing:" -> stringResource(fm.corus.android.localization.CorusStrings.map_sharing_label)
    "Shop official store" -> stringResource(fm.corus.android.localization.CorusStrings.parity_5926c3235507)
    "Show less" -> stringResource(fm.corus.android.localization.CorusStrings.concert_show_less)
    "Show more" -> stringResource(fm.corus.android.localization.CorusStrings.parity_25911d48e023)
    "Show on profile" -> stringResource(fm.corus.android.localization.CorusStrings.parity_67cf9791c36f)
    "Show trophies" -> stringResource(fm.corus.android.localization.CorusStrings.parity_9e2001f83002)
    "Show trophies on profile" -> stringResource(fm.corus.android.localization.CorusStrings.parity_8c123a5c30ec)
    "Show your city on the map" -> stringResource(fm.corus.android.localization.CorusStrings.parity_05441bc169a5)
    "Single" -> stringResource(fm.corus.android.localization.CorusStrings.parity_dd1186892a2f)
    "Sold out" -> stringResource(fm.corus.android.localization.CorusStrings.parity_02ff65909856)
    "Something went wrong. Please try again." -> stringResource(fm.corus.android.localization.CorusStrings.auth_error_generic)
    "Stop playback" -> stringResource(fm.corus.android.localization.CorusStrings.parity_3ee7638fbe65)
    "Stop sharing" -> stringResource(fm.corus.android.localization.CorusStrings.parity_0e45aee6e595)
    "Submit request" -> stringResource(fm.corus.android.localization.CorusStrings.parity_8a9051c61379)
    "Submitting a request does not automatically verify you or give you control of the artist page." -> stringResource(fm.corus.android.localization.CorusStrings.parity_5f7df6ce6b18)
    "Submitting…" -> stringResource(fm.corus.android.localization.CorusStrings.feedback_submitting)
    "Taste Matches" -> stringResource(fm.corus.android.localization.CorusStrings.feed_mode_taste_matches)
    "Taste Matches feed" -> stringResource(fm.corus.android.localization.CorusStrings.parity_f035d9bdea71)
    "Taste matches" -> stringResource(fm.corus.android.localization.CorusStrings.rail_taste_matches)
    "This is a place for people in %@ to connect." -> stringResource(R.string.parity_27338a83d773)
    "Tour dates" -> stringResource(fm.corus.android.localization.CorusStrings.parity_6c50d32835d2)
    "Unlike" -> stringResource(fm.corus.android.localization.CorusStrings.parity_e4fc40926893)
    "Unlimited posts" -> stringResource(fm.corus.android.localization.CorusStrings.parity_29a7a1e058da)
    "Unlimited saves" -> stringResource(fm.corus.android.localization.CorusStrings.parity_4cb955a437ea)
    "Upcoming shows" -> stringResource(fm.corus.android.localization.CorusStrings.parity_8d6779fdd977)
    "Use my city" -> stringResource(fm.corus.android.localization.CorusStrings.parity_5216b7ce77f3)
    "Verification" -> stringResource(fm.corus.android.localization.CorusStrings.parity_03128bed9062)
    "View Map" -> stringResource(fm.corus.android.localization.CorusStrings.parity_7e06a4c7c4de)
    "Watch" -> stringResource(fm.corus.android.localization.CorusStrings.parity_d91ebf5887cf)
    "Watch Mode" -> stringResource(fm.corus.android.localization.CorusStrings.parity_0c1b3cced072)
    "Watch anything good lately?" -> stringResource(fm.corus.android.localization.CorusStrings.parity_00ec7c4bb4f0)
    "Watch films posted by people in the countries you choose." -> stringResource(fm.corus.android.localization.CorusStrings.parity_04036d115a9a)
    "Watch preview · %lld trailers left · Explore Club" -> stringResource(R.string.parity_3525761a57be)
    "Watch trailer on YouTube" -> stringResource(fm.corus.android.localization.CorusStrings.parity_ed7a37f4f2d4)
    "What are you listening to?" -> stringResource(fm.corus.android.localization.CorusStrings.parity_7cc4c50bed35)
    "Who can see your city" -> stringResource(fm.corus.android.localization.CorusStrings.parity_1b527ff0e65e)
    "Yearly" -> stringResource(fm.corus.android.localization.CorusStrings.club_plan_yearly)
    "Yellow" -> stringResource(fm.corus.android.localization.CorusStrings.style_vinyl_yellow)
    "Your details" -> stringResource(fm.corus.android.localization.CorusStrings.parity_a6252b66904c)
    "Your posts" -> stringResource(fm.corus.android.localization.CorusStrings.parity_a1a5b173e056)
    "follower" -> stringResource(fm.corus.android.localization.CorusStrings.parity_12de88176aaf)
    "followers" -> stringResource(fm.corus.android.localization.CorusStrings.hashtag_followers)
    "following" -> stringResource(fm.corus.android.localization.CorusStrings.profile_stat_following)
    "more" -> stringResource(fm.corus.android.localization.CorusStrings.parity_e7c95b4c2824)
    else -> text
}
